version: "3.3"
services:
  api:
    build: ./api/
    container_name: python_api
    ports:
      - 5000:5000
    env_file:
      - credentials.env
  db:
    image: postgres
    container_name: database
    restart: always
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    env_file:
      - credentials.env
    ports:
      - 5432:5432